title: Safety Overview
description: Safety overview slides and quiz
template:
  repo: safety-overview-template
  name: safety-overview
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
